routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionsController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

Route::resource ('questions', QuestionsController::class)->except('show');


Route::get('/questions/{slug}', [QuestionsController::class, 'show'])->name('questions.show');

Route::resource('questions.answers', AnswerController::class)->except(['show', 'index', 'create']);

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected static function booted(): void {
        static::created(function (Answer $answer) {
            $answer->question->increment('answers_count');
        });
    }

    public function question() {
        return $this->belongsTo(Question::class);
    }

    public function author() {
        return $this->belongsTo(User::class, 'user_id');
    }
    
    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }
}

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Question extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function owner(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function answers(){
        return $this->hasMany(Answer::class);
    }
    public function getUrlAttribute() {
        return "questions/{$this->slug}";
    }

    public function getCreateDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    public function getAnswerStyleAttribute() {
        if($this->answers_count > 0) {
            if($this->best_answer_id) {
                return "has-best-answer";
            }
            return "answered";
        }
        return "unanswered";
    }

    public function setTitleAttribute($title){
        $this -> attributes['title'] = $title;
        $this -> attributes['slug'] = Str::slug($title);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    public function questions(){
        return $this->hasMany(Question::class);
    }
    public function answers(){
        return $this->hasMany(Answer::class);
    }
    public function getAvatarAttribute() {
        $size = 40;
        return "https://ui-avatars.com/api/?background=random&name={$this->name}&rounded=true&size={$size}";
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateQuestionRequest;
use App\Http\Requests\UpdateQuestionRequest;
use App\Models\Question;
use Illuminate\Routing\Controllers\HasMiddleware;
use Illuminate\Routing\Controllers\Middleware;
use Illuminate\Support\Facades\Gate;

class QuestionsController extends Controller
implements HasMiddleware
{
    public static function middleware(): array {
        return [
            new Middleware('auth', only:['store', 'create']),
            new Middleware('trackQuestionViews', only:['show'])

        ];
    }
    public function index(){
        $questions = Question::with('owner')->latest()->paginate(30);
        return view('qa.questions.index', compact(['questions']));
    }

    public function create() {
        // dd( auth()->user()->questions());
        return view('qa.questions.create');
    }

    public function store(CreateQuestionRequest $request) {
      auth()->user()->questions()->create([
            'title'=>$request->title,
            'body' => $request->body
        ]);
        // dd(auth()->user());

        session()->flash('success', 'Question has been added successfully!');
        return redirect(route('questions.index'));
    }
    public function update( UpdateQuestionRequest $request, Question $question) {
        $question->update([
            'title'=>$request->title,
            'body' => $request->body
        ]);
        session()->flash('success', 'Question has been updated successfully');
        return redirect(route('questions.index'));
    }

    public function destroy(Question $question) {
        Gate::authorize('delete',$question);
        $question->delete();
        session()->flash('success', 'Question has been deleted successfully!');
        return redirect(route('questions.index'));

    }

    public function edit(Question $question){
        //old method
         // if(! Gate::allows('update', $question)){
        //     abort(403);
        // }

        //new method
        Gate::authorize('update', $question);
        return view('qa.questions.edit', compact(['question']));
    }
    public function show(Question $question) {
    // dd('hello');
        return view('qa.questions.show', compact(['question']));
    }
}

resources/views/qa/questions/create.blade.php
@extends('qa.layouts.app')

@section('page-level-styles')
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.8/dist/trix.css">
@endsection

@section('page-level-script')
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
@endsection


@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h2>Ask a Question</h2>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('questions.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                             <div class="form-group mb-4">
                                <Label for="title" class="form-label">Title</Label>
                                <input type="text" name="title" id="title" placeholder="Enter Question Title!" value="{{ old('title') }} " class="form-control {{-- $error->has('title') ? 'is-invalid' : '' --}} " >
                                @error('title')
                                    <div class="text-danger text-sm">{{ $message }}</div>
                                @enderror
                            </div>
                           {{-- <div class="form-group mb-4">
                                <Label for="body" class="form-label">Enter your Question</Label>
                                <input id="x" type="hidden" name="body2" id="body3" />
                                <trix-editor input="x"class="form-label" name="body" id="body" class="form-control"></trix-editor>
                                @error('body')
                                    <div class="text-danger text-sm">{{ $message }}</div>
                                @enderror
                            </div> --}}
                            <div class="form-group mb-4">
                                <label for="body" class="form-label">Enter your Question</label>
                                <input id="body" type="hidden" name="body" value="{{ old('body')}}">
                                <trix-editor input="body" type="text"class="form-control {{ $errors->has('body') ? 'is-invalid' : ''}}" ></trix-editor>
                                @error('body')
                                <div class="text-danger text-sm">{{ $message }}</div>
                                @enderror
                            </div>


                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/qa/questions/edit.blade.php
@extends("qa.layouts.app")

@section('page-level-styles')
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.8/dist/trix.css">
@endsection

@section('page-level-script')
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h2>Ask a Question!</h2>
                    </div>

                    <div class="card-body">
                        <form action="{{route('questions.update', $question->id)}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group mb-4">
                                <label for="title" class="form-label">Title</label>
                                <input type="text" name="title" id="title" placeholder="Enter Question Title!"
                                value="{{old('title', $question->title)}}" class="form-control
                                {{$errors->has('title') ? 'is-invalid' : ''}}">

                                @error('title')
                                    <div class="text-danger text-sm">{{$message}}</div>
                                @enderror
                            </div>
                            <div class="form-group mb-4">
                                <label for="body" class="form-label">Enter your Question</label>
                                <input id="body" type="hidden" name="body" value="{{ old('body', $question)}}">
                                <trix-editor input="body" type="text"class="form-control {{ $errors->has('body') ? 'is-invalid' : ''}}" ></trix-editor>
                                @error('body')
                                <div class="text-danger text-sm">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-primary">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/qa/questions/index.blade.php
@extends('qa.layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <h2>All Question</h2>
                        <a href="{{ route('questions.create')}}" class="btn btn-outline-primary d-flex align-items-center"> Ask a Question! </a>
                    </div>
                    <div class="row">

                        @foreach ($questions as $question)
                          <div class="col-md-2">
                            <div class="d-flex flex-column mr-4 statistics">
                                <div class="votes text-center mb-3">
                                    <strong class="d-block">
                                        {{  $question->votes_count }}
                                    </strong>
                                    Votes
                                </div>
                                <div class="text-center mb-3">
                                    <strong class="answers {{  $question->answer_style  }} d-block" style="max-width: 60%; margin: 0 auto;">
                                        {{  $question->answers_count }}
                                    </strong>
                                    Answers
                                </div>
                                <div class="views text-center mb-3">
                                    <strong class="d-block">
                                        {{  $question->views_count }}
                                    </strong>
                                    Views
                                </div>
                            </div>
                          </div>
                          <div class="col-md-10">
                            <div class="card-body">
                                <div class="card-title">
                                    <div class="d-flex justify-content-between">
                                        <h3><a href="{{ $question->url }}">{{  $question->title  }}</a></h3>
                                        <div class="">
                                            <a href="{{ route('questions.edit', $question->id) }}" class="btn btn-sm btn-outline-warning">Edit</a>
                                            <form action="{{ route('questions.destroy', $question->id ) }}" class="d-inline-block" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-sm btn-outline-danger">Del</button>
                                            </form>
                                        </div>
                                    </div>
                                    <p>
                                        Asked By: <a href="a">
                                            {{ $question->owner->name }}
                                             <span class="text-muted">{{$question->created_date}}</span>
                                        </a>
                                    </p>
                                    <p>
                                        {!!  \Illuminate\Support\Str::limit($question->body, 250) !!}
                                    </p>

                                </div>
                            </div>
                          </div>
                            <hr/>
                        @endforeach
                    </div>


                    <div class="card-footer">
                        {{  $questions->links()  }}
                    </div>
                </div>
            </div>
        </div>
    </div>



@endsection

resources/views/qa/questions/show.blade.php
@extends('qa.layouts.app')
@section('page-level-styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.8/dist/trix.css">
@endsection

@section('page-level-script')
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h1>
                            {{ $question->title}}
                        </h1>
                    </div>
                    <div class="card-body">
                        <p>
                            {!! $question->body !!}
                        </p>
                    </div>

                    <div class="card-footer">
                        <div class="d-flex justify-content-between mr-3">
                            <div class="d-flex">
                                <div class="me-3">
                                    <a href="#" title="Up Vote" class="vote-up d-block text-center text-dark">
                                        <i class="fa fa-caret-up fa-3x"></i>
                                    </a>
                                    <h4 class="votes-count textmuted text-center m-0">{{ $question->votes_count }} </h4>
                                    <a href="#" title="Down Vote" class="vote-up d-block text-center text-dark">
                                        <i class="fa fa-caret-down fa-3x"></i>
                                    </a>
                                </div>
                                <div class="ml-4 mt-2">
                                    <a href="#" title="Mark as Fav">
                                        <i class="fa fa-star fa-2x text-dark"></i>
                                    </a>
                                    <h4>123</h4>
                                </div>
                            </div>
                            <div class="d-flex flex-column">
                                <div class="text-muted mb-2 text-right">
                                    Asked At: {{$question->create_date}}
                                </div>
                                <div class="d-flex mb-2">
                                    <div class="me-2">
                                        <img src="{{ $question->owner->avatar }}" alt="Avatar of {{ $question->owner->name }}"  >
                                    </div>
                                    <div class="mt-2 ml-2">
                                        {{ $question->owner->name}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @auth
            @include('qa.answers.partials._create')
        @endauth
        @include('qa.answers.partials._index')
    </div>

@endsection