routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionsController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

Route::resource ('questions', QuestionsController::class)->except('show');


Route::get('/questions/{slug}', [QuestionsController::class, 'show'])->name('questions.show');

Route::resource('questions.answers', AnswerController::class)->except(['show', 'index', 'create']);

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected static function booted(): void {
        static::created(function (Answer $answer) {
            $answer->question->increment('answers_count');
        });
    }

    public function question() {
        return $this->belongsTo(Question::class);
    }

    public function author() {
        return $this->belongsTo(User::class, 'user_id');
    }
    
    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateAnswerRequest;
use App\Http\Requests\UpdateAnswerRequest;
use App\Models\Answer;
use App\Models\Question;
use Illuminate\Http\Request;

class AnswerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateAnswerRequest $request, Question $question)
    {
        $question->answers()->create([
            'body'=>$request->body,
            'user_id'=>auth()->id()
        ]);

        session()->flash('success', 'Your Answer submitted successfully');
        return redirect($question->url);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Question $question, Answer $answer)
    {
        return view('qa.answers.edit', compact(['question', 'answer']));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateAnswerRequest $request, Question $question, Answer $answer)
    {
        dd('hllo');
        $answer->update([
            'body' => $request->body
        ]);

        session()->flash('success', 'Your Answer has been updated successfully');
        return redirect($question->url);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Question $question, Answer $answer)
    {
        $answer->delete();

        session()->flash('success', 'Your Answer has been deleted successfully');
        return redirect($question->url);
    }
}

resources/views/qa/answers/edit.blade.php
@extends("qa.layouts.app")

@section('page-level-styles')
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.8/dist/trix.css">
@endsection

@section('page-level-script')
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h2>Edit Answer!</h2>
                    </div>

                    <div class="card-body">
                        <form action="{{route('questions.answers.update',[$question, $answer])}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group mb-4">
                                <label for="body" class="form-label">Edit your Answer</label>
                                <input id="body" type="hidden" name="body" value="{{ old('body', $answer->body)}}">
                                <trix-editor input="body" type="text"class="form-control {{ $errors->has('body') ? 'is-invalid' : ''}}" ></trix-editor>
                                @error('body')
                                <div class="text-danger text-sm">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-primary">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection