routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionsController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

Route::resource ('questions', QuestionsController::class)->except('show');


Route::get('/questions/{slug}', [QuestionsController::class, 'show'])->name('questions.show');

Route::resource('questions.answers', AnswerController::class)->except(['show', 'index', 'create']);

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected static function booted(): void {
        static::created(function (Answer $answer) {
            $answer->question->increment('answers_count');
        });
    }

    public function question() {
        return $this->belongsTo(Question::class);
    }

    public function author() {
        return $this->belongsTo(User::class, 'user_id');
    }
    
    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    public function questions(){
        return $this->hasMany(Question::class);
    }
    public function answers(){
        return $this->hasMany(Answer::class);
    }
    public function getAvatarAttribute() {
        $size = 40;
        return "https://ui-avatars.com/api/?background=random&name={$this->name}&rounded=true&size={$size}";
    }
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateAnswerRequest;
use App\Http\Requests\UpdateAnswerRequest;
use App\Models\Answer;
use App\Models\Question;
use Illuminate\Http\Request;

class AnswerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateAnswerRequest $request, Question $question)
    {
        $question->answers()->create([
            'body'=>$request->body,
            'user_id'=>auth()->id()
        ]);

        session()->flash('success', 'Your Answer submitted successfully');
        return redirect($question->url);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Question $question, Answer $answer)
    {
        return view('qa.answers.edit', compact(['question', 'answer']));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateAnswerRequest $request, Question $question, Answer $answer)
    {
        dd('hllo');
        $answer->update([
            'body' => $request->body
        ]);

        session()->flash('success', 'Your Answer has been updated successfully');
        return redirect($question->url);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Question $question, Answer $answer)
    {
        $answer->delete();

        session()->flash('success', 'Your Answer has been deleted successfully');
        return redirect($question->url);
    }
}

resources/views/qa/answers/partials/_create.blade.php
        <div class="row mt-4 justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h2>Your Answer!</h2>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('questions.answers.store', $question->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group mb-4">
                                <input id="body" type="hidden" name="body" value="{{ old('body')}}">
                                <trix-editor input="body" type="text"class="form-control {{ $errors->has('body') ? 'is-invalid' : ''}}" ></trix-editor>
                                @error('body')
                                <div class="text-danger text-sm">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

resources/views/qa/answers/partials/_index.blade.php
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3>
                    {{ \Illuminate\Support\Str::plural('Answer', $question->answers_count) }}
                </h3>
            </div>
            <div class="card-body">

                @foreach ($question->answers as $answer )
                    <p>
                        {!! $answer->body !!}
                    </p>
                    <div class="d-flex justify-content-between mr-3">
                        <div class="d-flex flex-column">
                            @can('update', $answer)
                                <div class="">
                                    <a href="{{ route('questions.answers.edit', [$question, $answer]) }}"  class="btn btn-outline-warning btn-sm">Wdit</a>
                                </div>
                            @endcan
                            @can('delete', $answer)
                                <div class="">
                                    <form action="{{ route('questions.answers.destroy', [$question, $answer]) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-outline-danger btn-sm">Del</button>

                                    </form>
                                </div>
                            @endcan
                            <div class="me-3">
                                <a href="#" title="Up Vote" class="vote-up d-block text-center text-dark">
                                    <i class="fa fa-caret-up fa-3x"></i>
                                </a>
                                <h4 class="votes-count textmuted text-center m-0">{{ $answer->votes_count }} </h4>
                                <a href="#" title="Down Vote" class="vote-up d-block text-center text-dark">
                                    <i class="fa fa-caret-down fa-3x"></i>
                                </a>
                            </div>
                            <div class="ml-4 mt-2">
                                <a href="#" title="Mark as Fav">
                                    <i class="fa fa-star fa-2x text-dark"></i>
                                </a>
                                <h4>123</h4>
                            </div>

                        </div>
                        <div class="d-flex flex-column">
                            <div class="text-muted mb-2 text-right">
                                Answered At: {{$answer->created_date}}
                            </div>
                            <div class="d-flex mb-2">
                                <div class="me-2">
                                    <img src="{{ $answer->author->avatar }}" alt="Avatar of {{ $answer->author->name }}"  >
                                </div>
                                <div class="mt-2 ml-2">
                                    {{ $answer->author->name}}
                                </div>
                            </div>
                        </div>
                    </div>
                <hr>
                @endforeach
            </div>
        </div>
    </div>
</div>